# This is a Docker Compose configuration for local use.

# Run all services:
# docker compose up --build --wait

services:
  mongodb:
    # See more: https://hub.docker.com/_/mongo
    image: "mongo:8.0"
    restart: no
    ports:
      - "27017:27017"
    volumes:
      - "mongodb:/data/db"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/local --quiet
      timeout: 5s
      start_period: 30s
      interval: 1m
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-onezeroeight}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-herewethinkbig}

  minio:
    # See more: https://hub.docker.com/r/minio/minio
    image: "minio/minio:RELEASE.2024-05-10T01-41-38Z"
    restart: no
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "minio:/data"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-onezeroeight}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-herewethinkbig}

  maps:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        APP_MODULE: src.maps.app:app
    restart: no
    ports:
      - "8009:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro"
    deploy:
      # Change limits if project needs more RAM, though try to stay within limits
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

  clubs:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        APP_MODULE: src.clubs.app:app
    restart: no
    ports:
      - "8014:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro"
    deploy:
      # Change limits if project needs more RAM, though try to stay within limits
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_started

  student-affairs:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        APP_MODULE: src.student_affairs.app:app
    restart: no
    ports:
      - "8015:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro"
    deploy:
      # Change limits if project needs more RAM, though try to stay within limits
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

  when2meet:
    build:
      context: .
      dockerfile: api.Dockerfile
      args:
        APP_MODULE: src.when2meet.app:app
    restart: no
    ports:
      - "8020:8000"
    volumes:
      - "./settings.yaml:/app/settings.yaml:ro"
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 500m

volumes:
  mongodb:
  minio:
