import datetime as dtm
import hashlib
import re
from zoneinfo import ZoneInfo

import icalendar

from src.schedule_assistant.modules.issues.schemas import OccurrencePlacement, ScheduledMeeting

TIMEZONE = ZoneInfo("Europe/Moscow")


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.strip().casefold()).strip("-")
    return slug or hashlib.sha256(value.encode()).hexdigest()[:16]


def group_alias(group_kind: str, group_code: str) -> str:
    return f"{_slug(group_kind)}-{_slug(group_code)}"


def base_calendar(name: str) -> icalendar.Calendar:
    calendar = icalendar.Calendar()
    calendar.add("prodid", "-//one-zero-eight//Schedule Assistant//EN")
    calendar.add("version", "2.0")
    calendar.add("method", "PUBLISH")
    calendar.add("x-wr-calname", name)
    calendar.add("x-wr-caldesc", "Generated by InNoHassle Schedule Assistant")
    calendar.add("x-wr-timezone", "Europe/Moscow")
    return calendar


def _instructors(
    value: str | list[str] | None,
    instructor_names: dict[str, str],
) -> str | None:
    values = value if isinstance(value, list) else [value] if value is not None else []
    labels = [instructor_names.get(item.strip().casefold(), item.strip()) for item in values if item.strip()]
    if isinstance(value, list):
        joined = ", ".join(labels)
        return joined or None
    return labels[0] if labels else None


def _clock_time(value: dtm.time) -> dtm.time:
    return value.replace(tzinfo=None)


def _uid(alias: str, meeting: ScheduledMeeting) -> str:
    if not isinstance(meeting.placement, OccurrencePlacement):
        raise TypeError("ICS generation requires concrete meeting dates")
    identity = "\x1f".join(
        [
            alias,
            meeting.course_name,
            meeting.component_tag,
            meeting.placement.date.isoformat(),
            _clock_time(meeting.start_time).isoformat(),
            _clock_time(meeting.end_time).isoformat(),
            *meeting.groups,
        ]
    )
    digest = hashlib.sha256(identity.encode()).hexdigest()
    return f"{digest}@innohassle.ru"


def add_meeting(
    calendar: icalendar.Calendar,
    alias: str,
    meeting: ScheduledMeeting,
    instructor_names: dict[str, str],
) -> None:
    if not isinstance(meeting.placement, OccurrencePlacement):
        raise TypeError("ICS generation requires concrete meeting dates")
    event = icalendar.Event()
    event.add("uid", _uid(alias, meeting))
    event.add("dtstamp", dtm.datetime(1970, 1, 1, tzinfo=dtm.UTC))
    event.add(
        "dtstart",
        dtm.datetime.combine(meeting.placement.date, _clock_time(meeting.start_time), tzinfo=TIMEZONE),
    )
    event.add(
        "dtend",
        dtm.datetime.combine(meeting.placement.date, _clock_time(meeting.end_time), tzinfo=TIMEZONE),
    )
    event.add("summary", f"{meeting.course_name} ({meeting.component_tag})")
    if meeting.room and meeting.room.strip():
        event.add("location", meeting.room.strip())
    description: list[str] = []
    if instructors := _instructors(meeting.instructor, instructor_names):
        description.append(f"Instructor: {instructors}")
    if meeting.groups:
        description.append(f"Groups: {', '.join(meeting.groups)}")
    if description:
        event.add("description", "\n".join(description))
    calendar.add_component(event)


def render_calendar(
    calendar_name: str,
    alias_meetings: list[tuple[str, ScheduledMeeting]],
    instructor_names: dict[str, str] | None = None,
) -> bytes:
    calendar = base_calendar(calendar_name)
    resolved_instructor_names = instructor_names or {}
    for alias, meeting in sorted(
        alias_meetings,
        key=lambda item: (
            item[1].placement.date if isinstance(item[1].placement, OccurrencePlacement) else dtm.date.min,
            item[1].start_time,
            item[0],
            item[1].course_name,
            item[1].component_tag,
        ),
    ):
        add_meeting(calendar, alias, meeting, resolved_instructor_names)
    return calendar.to_ical(sorted=True)
