import os
import subprocess  # noqa: S404
import sys
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from yaml import safe_dump

ALEMBIC_INI = Path(__file__).parents[2] / "src/schedule_assistant/alembic.ini"


def _config(database_url: str) -> Config:
    config = Config(ALEMBIC_INI)
    config.attributes["sqlalchemy.url"] = database_url
    return config


@pytest.mark.parametrize("configuration_source", ["url_attribute", "settings_path"])
def test_empty_upgrade_repeat_head_and_metadata_check(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    configuration_source: str,
) -> None:
    settings_path = tmp_path / "settings.yaml"
    monkeypatch.setenv("SETTINGS_PATH", str(settings_path))
    config = _config(migration_database_url)
    if configuration_source == "settings_path":
        settings_path.write_text(safe_dump({"schedule_assistant_service": {"db_url": migration_database_url}}))
        config.attributes.clear()

    command.upgrade(config, "head")
    head = ScriptDirectory.from_config(config).get_current_head()
    engine = sa.create_engine(migration_database_url)
    try:
        with engine.begin() as connection:
            assert connection.scalar(sa.text("SELECT version_num FROM alembic_version")) == head
            connection.execute(sa.text("INSERT INTO config_meta (id, revision) VALUES (1, 42)"))

        command.upgrade(config, "head")
        with engine.connect() as connection:
            assert connection.execute(sa.text("SELECT id, revision FROM config_meta")).all() == [(1, 42)]
            assert connection.scalar(sa.text("SELECT version_num FROM alembic_version")) == head
        command.check(config)
    finally:
        engine.dispose()


def test_connection_injection_does_not_read_settings(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("SETTINGS_PATH", str(tmp_path / "missing-settings.yaml"))
    engine = sa.create_engine(migration_database_url)
    try:
        with engine.begin() as connection:
            config = Config(ALEMBIC_INI, attributes={"connection": connection})
            command.upgrade(config, "head")
            command.check(config)
            assert connection.scalar(sa.text("SELECT version_num FROM alembic_version"))
            assert not connection.closed
    finally:
        engine.dispose()


def test_populated_predecessor_upgrade_preserves_data_and_drops_history(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("SETTINGS_PATH", str(tmp_path / "missing-settings.yaml"))
    config = _config(migration_database_url)
    command.upgrade(config, "n4h5i6j7k8l9")
    engine = sa.create_engine(migration_database_url)
    try:
        with engine.begin() as connection:
            connection.execute(sa.text("INSERT INTO config_meta (id, revision) VALUES (1, 42)"))
            connection.execute(
                sa.text(
                    "INSERT INTO courses (name, section_code, instructors, components) "
                    "VALUES ('Algorithms', 'core', '[]', '[]')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO student_groups (code, name, estimated_size, students) "
                    "VALUES ('B26', 'Bachelor 2026', 24, '[\"student@example.test\"]')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO instructors (id, name_en, name_ru, email, alias, position, slot_preferences) "
                    "VALUES ('alice', 'Alice', 'Алиса', 'alice@example.test', 'alice', 'Professor', '[]')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO rooms (id, name, capacity, features) VALUES ('108', 'Lecture Room 108', 312, '{}')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO booking_tasks "
                    "(id, kind, status, sent, done, total, current, items, result, error, created_at, updated_at) "
                    "VALUES ('task-1', 'book', 'completed', 0, 0, 0, NULL, '[]', NULL, NULL, "
                    "'2026-09-01T12:00:00+00', '2026-09-01T12:00:00+00')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO booking_operations "
                    "(id, reservation_key, task_id, item, created_at, updated_at) "
                    "VALUES ('op-1', 'reservation-1', 'task-1', '{}', "
                    "'2026-09-01T12:00:00+00', '2026-09-01T12:00:00+00')"
                )
            )
            connection.execute(
                sa.text(
                    "INSERT INTO config_history_events (id, revision, resources, saved_at, saved_by, patch, snapshot) "
                    "VALUES ('history', 42, '[\"courses\"]', '2026-09-01T12:00:00Z', 'instructor', '[]', "
                    '\'{"courses": [{"name": "Algorithms", "components": []}]}\')'
                )
            )
            groups = connection.execute(sa.text("SELECT * FROM student_groups")).all()
            instructors = connection.execute(sa.text("SELECT * FROM instructors")).all()
            rooms = connection.execute(sa.text("SELECT * FROM rooms")).all()
            booking_tasks = connection.execute(sa.text("SELECT * FROM booking_tasks")).all()
            booking_operations = connection.execute(sa.text("SELECT * FROM booking_operations")).all()
            assert connection.scalar(sa.text("SELECT count(*) FROM config_history_events")) == 1

        command.upgrade(config, "head")
        with engine.connect() as connection:
            assert connection.execute(sa.text("SELECT id, revision FROM config_meta")).all() == [(1, 42)]
            assert connection.execute(sa.text("SELECT * FROM student_groups")).all() == groups
            assert connection.execute(sa.text("SELECT * FROM instructors")).all() == instructors
            assert connection.execute(sa.text("SELECT * FROM rooms")).all() == rooms
            assert connection.execute(sa.text("SELECT * FROM booking_tasks")).all() == booking_tasks
            assert connection.execute(sa.text("SELECT * FROM booking_operations")).all() == booking_operations
            assert connection.execute(
                sa.text("SELECT name, section_code, color, instructors, components FROM courses")
            ).all() == [("Algorithms", "core", None, [], [])]
            assert not sa.inspect(connection).has_table("config_history_events")
            assert connection.scalar(sa.text("SELECT version_num FROM alembic_version")) == "o5i6j7k8l9m0"

        command.upgrade(config, "head")
        with engine.connect() as connection:
            assert connection.execute(sa.text("SELECT id, revision FROM config_meta")).all() == [(1, 42)]
            assert not sa.inspect(connection).has_table("config_history_events")
        command.check(config)

        with pytest.raises(NotImplementedError, match="Cannot restore config_history_events"):
            command.downgrade(config, "n4h5i6j7k8l9")
    finally:
        engine.dispose()


def test_standalone_environment_registers_model_metadata(migration_database_url: str, tmp_path: Path) -> None:
    result = subprocess.run(  # noqa: S603 - Execute fixed test code against the isolated test database.
        [
            sys.executable,
            "-c",
            (
                "import sys; from alembic import command; from alembic.config import Config; "
                "config = Config(sys.argv[1], attributes={'sqlalchemy.url': sys.argv[2]}); "
                "command.upgrade(config, 'head'); command.check(config)"
            ),
            str(ALEMBIC_INI),
            migration_database_url,
        ],
        cwd=ALEMBIC_INI.parents[2],
        env={**os.environ, "SETTINGS_PATH": str(tmp_path / "missing-settings.yaml")},
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_metadata_check_detects_schema_drift(migration_database_url: str) -> None:
    config = _config(migration_database_url)
    command.upgrade(config, "head")
    engine = sa.create_engine(migration_database_url)
    try:
        with engine.begin() as connection:
            connection.execute(sa.text("ALTER TABLE courses DROP COLUMN color"))
        with pytest.raises(AutogenerateDiffsDetected, match="color"):
            command.check(config)
    finally:
        engine.dispose()
