import asyncio
from pathlib import Path

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy.ext.asyncio import create_async_engine
from yaml import safe_dump

ALEMBIC_INI = Path(__file__).parents[2] / "src/schedule/alembic.ini"


def _config(database_url: str) -> Config:
    config = Config(ALEMBIC_INI)
    config.attributes["sqlalchemy.url"] = database_url
    return config


async def _execute(database_url: str, statement: str) -> list[sa.Row]:
    engine = create_async_engine(database_url)
    try:
        async with engine.begin() as connection:
            result = await connection.execute(sa.text(statement))
            return list(result) if result.returns_rows else []
    finally:
        await engine.dispose()


@pytest.mark.parametrize("configuration_source", ["url_attribute", "settings_path"])
def test_empty_upgrade_repeat_head_and_metadata_check(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    configuration_source: str,
) -> None:
    settings_path = tmp_path / "settings.yaml"
    monkeypatch.setenv("SETTINGS_PATH", str(settings_path))
    config = _config(migration_database_url)
    if configuration_source == "settings_path":
        settings_path.write_text(safe_dump({"schedule_service": {"db_url": migration_database_url}}))
        config.attributes.clear()

    command.upgrade(config, "head")
    head = ScriptDirectory.from_config(config).get_current_head()
    assert asyncio.run(_execute(migration_database_url, "SELECT version_num FROM alembic_version")) == [(head,)]
    asyncio.run(_execute(migration_database_url, "INSERT INTO users (email) VALUES ('preserved@example.test')"))
    before = asyncio.run(_execute(migration_database_url, "SELECT * FROM users"))

    command.upgrade(config, "head")
    assert asyncio.run(_execute(migration_database_url, "SELECT * FROM users")) == before
    assert asyncio.run(_execute(migration_database_url, "SELECT version_num FROM alembic_version")) == [(head,)]
    command.check(config)


def test_connection_injection_does_not_read_settings(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("SETTINGS_PATH", str(tmp_path / "missing-settings.yaml"))

    def upgrade(connection: sa.Connection) -> None:
        config = Config(ALEMBIC_INI, attributes={"connection": connection})
        command.upgrade(config, "head")
        command.check(config)
        assert connection.scalar(sa.text("SELECT version_num FROM alembic_version"))
        assert not connection.closed

    async def run() -> None:
        engine = create_async_engine(migration_database_url)
        try:
            async with engine.begin() as connection:
                await connection.run_sync(upgrade)
        finally:
            await engine.dispose()

    asyncio.run(run())


def test_populated_predecessor_upgrade_preserves_preferences(
    migration_database_url: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("SETTINGS_PATH", str(tmp_path / "missing-settings.yaml"))
    config = _config(migration_database_url)
    command.upgrade(config, "ae37e0d0ee10")
    statements = [
        "INSERT INTO users (id, email, name, innohassle_id) VALUES (1, 'student@example.test', 'Student', 'student')",
        "INSERT INTO event_groups (id, alias, name) VALUES (10, 'schedule-assistant-english-b2', 'English')",
        "INSERT INTO users_x_favorite_groups (user_id, group_id) VALUES (1, 10)",
        "INSERT INTO users_x_hidden_groups (user_id, group_id) VALUES (1, 10)",
        "INSERT INTO events (id, name, description) VALUES (20, 'Lecture', 'Preserve this event')",
    ]
    for statement in statements:
        asyncio.run(_execute(migration_database_url, statement))
    users = asyncio.run(_execute(migration_database_url, "SELECT * FROM users"))
    groups = asyncio.run(_execute(migration_database_url, "SELECT * FROM event_groups"))
    events = asyncio.run(_execute(migration_database_url, "SELECT * FROM events"))

    command.upgrade(config, "head")

    assert asyncio.run(_execute(migration_database_url, "SELECT * FROM users")) == users
    assert asyncio.run(_execute(migration_database_url, "SELECT * FROM event_groups")) == groups
    assert asyncio.run(_execute(migration_database_url, "SELECT * FROM events")) == events
    for statement in (
        "SELECT user_id, group_alias FROM users_x_favorite_groups",
        "SELECT user_id, group_alias FROM users_x_hidden_groups",
    ):
        assert asyncio.run(_execute(migration_database_url, statement)) == [(1, "english-b2")]
    command.check(config)


def test_metadata_check_detects_schema_drift(migration_database_url: str) -> None:
    config = _config(migration_database_url)
    command.upgrade(config, "head")
    asyncio.run(_execute(migration_database_url, "ALTER TABLE users DROP COLUMN name"))
    with pytest.raises(AutogenerateDiffsDetected, match="name"):
        command.check(config)
