"""Automated quality requirement tests (QRT-001..QRT-003) for When2Meet."""

import time
import xml.etree.ElementTree as ET
from pathlib import Path

import pytest
from starlette.testclient import TestClient

REPO_ROOT = Path(__file__).resolve().parents[2]
COVERAGE_XML = REPO_ROOT / "coverage.xml"

CRITICAL_MODULES = {
    "src/when2meet/modules/events/routes.py": 30.0,
    "src/when2meet/modules/events/events_repo.py": 30.0,
    "src/when2meet/modules/events/schemas.py": 30.0,
}

GET_EVENT_TIME_BUDGET_SECONDS = 2.0


def _line_rate_for_file(coverage_xml: Path, filename: str) -> float:
    tree = ET.parse(coverage_xml)
    normalized = filename.replace("\\", "/")
    for class_node in tree.findall(".//class"):
        class_filename = class_node.get("filename", "").replace("\\", "/")
        if class_filename.endswith(normalized) or normalized.endswith(class_filename):
            return float(class_node.get("line-rate", "0")) * 100.0
    pytest.fail(f"Critical module not found in {coverage_xml}: {filename}")


def test_qrt_critical_modules_line_coverage_meets_threshold():
    """QRT-001 verifies QR-001 Testability coverage scenarios."""
    if not COVERAGE_XML.is_file():
        pytest.skip("coverage.xml missing; generated by CI pytest job with --cov-report=xml")

    for module_path, minimum_percent in CRITICAL_MODULES.items():
        actual = _line_rate_for_file(COVERAGE_XML, module_path)
        assert actual >= minimum_percent, (
            f"{module_path} line coverage {actual:.1f}% is below required {minimum_percent:.1f}%"
        )


def test_qrt_non_owner_cannot_patch_or_delete_event(
    when2meet_client: TestClient,
    user_headers,
    auth_header_factory,
):
    """QRT-002 verifies QR-002 Confidentiality for owner-only mutations."""
    create_resp = when2meet_client.post(
        "/api/v0/events",
        json={"name": "QRT Owner Event", "slots": ["2026-06-15T10:00:00Z"]},
        headers=user_headers,
    )
    assert create_resp.status_code == 201
    event_id = create_resp.json()["id"]

    other_headers = auth_header_factory("qrt-other-user", "qrt-other@example.com")

    patch_resp = when2meet_client.patch(
        f"/api/v0/events/{event_id}",
        json={"name": "Unauthorized rename"},
        headers=other_headers,
    )
    assert patch_resp.status_code == 403

    delete_resp = when2meet_client.delete(f"/api/v0/events/{event_id}", headers=other_headers)
    assert delete_resp.status_code == 403

    owner_delete_resp = when2meet_client.delete(f"/api/v0/events/{event_id}", headers=user_headers)
    assert owner_delete_resp.status_code == 204


def test_qrt_get_event_completes_within_time_budget(when2meet_client: TestClient, user_headers):
    """QRT-003 verifies QR-003 Time behaviour for event detail reads."""
    create_resp = when2meet_client.post(
        "/api/v0/events",
        json={
            "name": "QRT Timing Event",
            "slots": ["2026-06-15T10:00:00Z", "2026-06-15T11:00:00Z"],
        },
        headers=user_headers,
    )
    assert create_resp.status_code == 201
    event_id = create_resp.json()["id"]

    started = time.monotonic()
    get_resp = when2meet_client.get(f"/api/v0/events/{event_id}", headers=user_headers)
    elapsed = time.monotonic() - started

    assert get_resp.status_code == 200
    assert elapsed <= GET_EVENT_TIME_BUDGET_SECONDS
