site_name: When2Meet Documentation
site_url: https://one-zero-eight.github.io/monorepo/
repo_url: https://github.com/one-zero-eight/monorepo
repo_name: one-zero-eight/monorepo
edit_uri: edit/main/src/when2meet/docs/
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
nav:
  - Home: index.md
  - Product:
      - Roadmap: roadmap.md
      - Interface: interface.md
      - User acceptance tests: user-acceptance-tests.md
  - Engineering:
      - Development process: development-process.md
      - Definition of Done: definition-of-done.md
      - Testing: testing.md
      - Quality requirements: quality-requirements.md
      - Quality requirement tests: quality-requirement-tests.md
  - Architecture:
      - Overview: architecture/README.md
      - ADRs: architecture/adr/README.md
