__all__ = [
    "TIMEZONE",
    "aware_utcnow",
    "get_base_calendar",
    "get_current_year",
    "locate_ics_by_path",
    "validate_calendar",
    "validate_vevent",
]

import datetime as dtm
from pathlib import Path, PurePath
from typing import Any, cast

import dateutil.rrule
import icalendar

from src.schedule.config import settings

TIMEZONE = "Europe/Moscow"


def get_current_year() -> int:
    """Returns current year."""
    return dtm.datetime.now(dtm.UTC).year


def validate_calendar(calendar: icalendar.Calendar):
    for component in calendar.walk("VEVENT"):
        validate_vevent(cast(icalendar.Event, component))


def validate_vevent(event: icalendar.Event):
    if "UID" not in event:
        raise ValueError("Event has no UID", event)

    vddd_dtstart: icalendar.vDDDTypes | None = event.get("DTSTART")
    vddd_dtend: icalendar.vDDDTypes | None = event.get("DTEND")
    vddd_duration: icalendar.vDDDTypes | None = event.get("DURATION")

    if not vddd_dtstart:
        raise ValueError("Event has no DTSTART", event)

    if not vddd_dtend and not vddd_duration and vddd_dtstart.params.get("VALUE") != "DATE":
        raise ValueError("Event has no DTEND or DURATION", event)

    if vddd_dtend and vddd_duration:
        raise ValueError("Event has both DTEND and DURATION", event)

    if vddd_dtend:
        dtstart = cast(dtm.date | dtm.datetime, vddd_dtstart.dt)
        dtend = cast(dtm.date | dtm.datetime, vddd_dtend.dt)
        if dtstart > dtend:
            raise ValueError("DTSTART is later than DTEND", event)

    if "RRULE" in event:
        rrule_raw = cast(Any, event["RRULE"]).to_ical()
        rrule_str = rrule_raw.decode() if isinstance(rrule_raw, bytes) else rrule_raw
        rrule: dateutil.rrule.rrule = dateutil.rrule.rrulestr(rrule_str, dtstart=vddd_dtstart.dt)
        rrule_dates = iter(rrule)
        rrule_first_dt = next(rrule_dates, None)

        if rrule_first_dt:
            rrule_first_date = rrule_first_dt.date()

            if isinstance(vddd_dtstart.dt, dtm.datetime):
                vdd_date = vddd_dtstart.dt.date()
            elif isinstance(vddd_dtstart.dt, dtm.date):
                vdd_date = vddd_dtstart.dt
            else:
                raise ValueError("DTSTART is not datetime or date", event)

            if rrule_first_date != vdd_date:
                raise ValueError("DTSTART is not compatible with RRULE", event)
        else:
            raise ValueError("RRULE produces empty list", event)


def aware_utcnow() -> dtm.datetime:
    return dtm.datetime.now(dtm.UTC)


def locate_ics_by_path(path: str) -> Path:
    normalized_path = PurePath(path)
    if normalized_path.is_absolute() or ".." in normalized_path.parts:
        raise ValueError(f"Path escapes predefined ICS directory: {path!r}")
    if not normalized_path.name or normalized_path.suffix != ".ics":
        raise ValueError(f"Path must point to an .ics file inside predefined/ics: {path!r}")

    base_dir = (settings.predefined_dir / "ics").resolve(strict=False)
    ics_path = (base_dir / normalized_path).resolve(strict=False)

    if not ics_path.is_relative_to(base_dir):
        raise ValueError(f"Path escapes predefined ICS directory: {path!r}")
    if ics_path.exists() and ics_path.is_dir():
        raise ValueError(f"Path must point to a file, not a directory: {path!r}")

    return ics_path


def get_base_calendar() -> icalendar.Calendar:
    """
    Get base calendar with default properties (version, prodid, etc.)
    :return: base calendar
    :rtype: icalendar.Calendar
    """

    calendar = icalendar.Calendar(
        prodid="-//one-zero-eight//InNoHassle Schedule",
        version="2.0",
        method="PUBLISH",
    )

    calendar["x-wr-caldesc"] = "Generated by InNoHassle Schedule"
    calendar["x-wr-timezone"] = TIMEZONE
    #
    # add timezone
    timezone = icalendar.Timezone(tzid=TIMEZONE)
    timezone["x-lic-location"] = TIMEZONE
    # add standard timezone
    standard = icalendar.TimezoneStandard()
    standard.add("tzoffsetfrom", dtm.timedelta(hours=3))
    standard.add("tzoffsetto", dtm.timedelta(hours=3))
    standard.add("tzname", "MSK")
    standard.add("dtstart", dtm.datetime(1970, 1, 1, tzinfo=dtm.UTC))
    timezone.add_component(standard)
    calendar.add_component(timezone)

    return calendar
