# This file should be synced with:
# https://github.com/one-zero-eight/accounts/blob/main/inh_accounts_sdk.py

import datetime as dtm
import logging
from logging import Logger
from typing import Any

import httpx
from joserfc import jwt
from joserfc.errors import JoseError
from joserfc.jwk import RSAKey
from joserfc.jwt import JWTClaimsRegistry
from pydantic import BaseModel, SecretStr


class TelegramInfo(BaseModel):
    id: int
    first_name: str
    last_name: str | None = None
    username: str | None = None
    photo_url: str | None = None
    updated_at: dtm.datetime


class InnopolisInfo(BaseModel):
    email: str
    name: str | None = None
    is_student: bool = False
    is_staff: bool = False
    is_college: bool = False
    updated_at: dtm.datetime


class UserSchema(BaseModel):
    id: str
    innopolis_info: InnopolisInfo
    telegram_info: TelegramInfo | None = None
    innohassle_admin: bool = False


class UserTokenData(BaseModel):
    innohassle_id: str
    "InNoHassle Accounts ID"
    email: str
    "Innopolis email (@innopolis.university or @innopolis.ru)"
    telegram_id: int | None = None
    "User's Telegram ID connected to InNoHassle Accounts"


class InNoHassleAccounts:
    api_url: str
    api_jwt_token: str | SecretStr | None
    mock: bool
    PUBLIC_KID = "public"
    key_set: dict[str, Any] | None = None
    _http: httpx.AsyncClient | None = None

    def __init__(
        self,
        api_url: str = "https://api.innohassle.ru/accounts/v0",
        api_jwt_token: str | SecretStr | None = None,
        mock: bool = False,
        logger: Logger | None = None,
    ):
        self.api_url = api_url
        self.api_jwt_token = api_jwt_token
        self.mock = mock
        if logger is None:
            logger = logging.getLogger(__name__)
        self.logger = logger
        if self.api_jwt_token is None:
            self.logger.warning(
                "InNoHassle Accounts API JWT token is not set, you will not be able to call service endpoints that require authorization"
            )

    def _ensure_http_client(self) -> httpx.AsyncClient:
        if self._http is None:
            headers: dict[str, str] = {}
            if self.api_jwt_token is not None:
                token = (
                    self.api_jwt_token.get_secret_value()
                    if isinstance(self.api_jwt_token, SecretStr)
                    else self.api_jwt_token
                )
                headers["Authorization"] = f"Bearer {token}"
            self._http = httpx.AsyncClient(base_url=self.api_url, headers=headers)
        return self._http

    async def aclose(self) -> None:
        if self._http is not None:
            await self._http.aclose()
            self._http = None

    async def update_key_set(self):
        if self.mock:
            self.key_set = {"keys": []}
            self.logger.warning("InNoHassle Accounts mock mode: JWKS fetch skipped")
            return
        self.logger.info("Updating key set for InNoHassle Accounts...")
        self.key_set = await self.get_key_set()
        self.logger.info("Key set updated successfully")

    def get_public_key(self) -> RSAKey:
        if self.key_set is None:
            raise RuntimeError("Key set should be initialized by `update_key_set`")
        key_data = next((key for key in self.key_set.get("keys", []) if key.get("kid") == self.PUBLIC_KID), None)
        if key_data is None:
            raise RuntimeError(f"Public key with kid={self.PUBLIC_KID!r} is missing in JWKS")
        return RSAKey.import_key(key_data)

    async def get_key_set(self) -> dict[str, Any]:
        client = self._ensure_http_client()
        response = await client.get("/.well-known/jwks.json")
        response.raise_for_status()
        return response.json()

    def decode_user_token(self, token: str) -> UserTokenData | None:
        """
        Decode generated by InnoHassle Accounts user JWT token and return user data.
        If token is invalid, return None.
        """
        if self.mock:
            raw = token.strip()
            if raw.startswith("{"):
                try:
                    return UserTokenData.model_validate_json(raw)
                except Exception:
                    self.logger.warning(f"Invalid mock Bearer JSON for UserTokenData: {raw}", exc_info=True)
                    return None
        try:
            payload = self._get_jwt_claims(token)
            innohassle_id: str | None = payload.get("uid")
            email: str | None = payload.get("email")
            telegram_id: int | None = payload.get("telegram_id")
            if innohassle_id is None or email is None:
                raise JoseError("Missing required claims: uid/email")
            return UserTokenData(
                innohassle_id=innohassle_id,
                email=email,
                telegram_id=telegram_id,
            )
        except JoseError:
            self.logger.warning("Invalid token", exc_info=True)
            return None

    def get_authorized_client(self) -> httpx.AsyncClient:
        if self.api_jwt_token is None:
            raise ValueError("API JWT token is not set")
        return self._ensure_http_client()

    def _get_jwt_claims(self, token: str) -> dict[str, Any]:
        pub_key = self.get_public_key()
        payload = jwt.decode(token, pub_key)
        claims = payload.claims
        JWTClaimsRegistry().validate(claims)
        return claims

    async def get_user(
        self,
        innohassle_id: str | None = None,
        email: str | None = None,
        telegram_id: int | None = None,
    ) -> UserSchema | None:
        """
        Get user by one of the provided identifiers.
        If multiple identifiers are provided, the first one that exists will be returned.
        """
        client = self.get_authorized_client()
        urls = []
        if innohassle_id:
            urls.append(f"/users/by-id/{innohassle_id}")
        if email:
            urls.append(f"/users/by-innomail/{email}")
        if telegram_id:
            urls.append(f"/users/by-telegram-id/{telegram_id}")
        for url in urls:
            response = await client.get(url)
            try:
                response.raise_for_status()
                return UserSchema.model_validate(response.json())
            except httpx.HTTPStatusError as e:
                if e.response.status_code == 404:
                    continue
                raise
        return None

    async def get_users(self, innohassle_ids: list[str]) -> dict[str, UserSchema | None]:
        """
        Get multiple users by ids.
        """
        client = self.get_authorized_client()
        response = await client.post("/users/by-id/get-bulk", json=innohassle_ids)
        response.raise_for_status()
        return {k: UserSchema.model_validate(v) if v else None for k, v in response.json().items()}


# Project specific code follows
import src.logging_  # noqa: E402
from src.config_root_schema import load_root_settings  # noqa: E402

root_settings = load_root_settings()

if root_settings.accounts:
    inh_accounts: InNoHassleAccounts = InNoHassleAccounts(
        api_url=root_settings.accounts.api_url,
        api_jwt_token=root_settings.accounts.api_jwt_token,
        mock=root_settings.accounts.mock,
        logger=src.logging_.logger,
    )
else:
    raise ImportError("InNoHassle Accounts is not configured in ./settings.yaml")  # pragma: no cover
# ^
