name: Links

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

jobs:
    linkChecker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Link Checker
              id: lychee
              uses: lycheeverse/lychee-action@v2
              with:
                  format: "markdown"
                  args: >-
                      . --verbose --exclude-all-private
                      --exclude 'https?://([^/]*\.)*innohassle\.ru'
                      --exclude 'https?://([^/]*\.)*iso\.org'
